### ISSUE TITLE
Cannot get working with WebPack

### ISSUE THREAD

**Issue by danawoodman** [superRaytin/react-monaco-editor#139] opened 2018-07-25 03:37 UTC
Getting the following error after importing MonacoEditor and setting up the WebPack plugin (I restarted WebPack after the change). Followed the readme as closely as I could.

![](https://cl.ly/tBp9/Screen%20Shot%202018-07-24%20at%208.36.02%20PM.png)

- Webpack v4.10.2
- React v16.4.0
- Node v10.3.0

Am I missing a setup step or something?

**Comment by domoritz** [comment] 2018-07-25 04:41
Does the example in this repo work for you?

**Comment by danawoodman** [comment] 2018-07-26 05:52
@domoritz you mean if I clone this repo and run the example in it?

**Comment by domoritz** [comment] 2018-07-26 12:49
Yes

**Comment by danawoodman** [comment] 2018-07-26 19:53
Yes, the example works for me

**Comment by domoritz** [comment] 2018-07-26 23:33
Can you see what's wrong with the webpack config or the specific versions you use then?

**Comment by danawoodman** [comment] 2018-07-27 00:01
I see nothing obvious. 

Example has WebPack `^4.8.3`, I have `v4.10.2`.

Both have the WebPack plugin enabled.

Both have latest `react-monaco-editor` and `monaco-editor-webpack-plguin`.

The error I'm getting comes from the initial WebPack build. If I remove the `import` statement from my code, I get no error (but no editor either). If I `import` Monaco editor, everything explodes as above.

**Comment by domoritz** [comment] 2018-07-27 00:44
What about your tsconfig?

**Comment by TheRealPiotrP** [comment] 2018-07-30 19:18
I'm seeing the same issue with the  same error on the same two files. Also using typescript. my tsconfig looks like this:

```
{
    "compilerOptions": {
        "allowJs": true,
        "experimentalDecorators": true,
        "jsx": "react",
        "lib": [ "es6", "dom" ],
        "module": "commonjs",
        "noImplicitAny": true,
        "outDir": "./obj",
        "sourceMap": true,
        "target": "es6",
        "pretty": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by TheRealPiotrP** [comment] 2018-07-30 19:32
some progress. I had the following in my cssloader configuration:
```
,
                        options: {
                            modules: true
                        }
```

Removing this  allowed the build to complete.

**Comment by TheRealPiotrP** [comment] 2018-07-30 20:04
disabling modules, unfortunately, breaks a number of features in the remainder of our build pipeline, so looking for other approaches...

**Comment by TheRealPiotrP** [comment] 2018-07-30 20:53
I tried running the sample from this repo and actually this fails as well:
```
ERROR in ../src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: Unknown plugin "transform-class-properties" specified in "C:\\code\\github\\superRaytin\\react-monaco-editor\\.babelrc" at 0, attempted to resolve relative to "C:\\code\\github\\superRaytin\\react-monaco-editor"
```

**Comment by domoritz** [comment] 2018-07-30 21:39
So why does the example work and your code does not? Is there something that react monaco can do?

**Comment by TheRealPiotrP** [comment] 2018-07-30 21:47
example works because it does not ask css-loader to build modules. my project does not work because it does. you can repro this in webpack.config.js, changing:
```
      {
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
      }
```
to
```
      {
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader?modules' ]
      }
```

it's not clear to me where this should be fixed. I'm writing down my `adventure` in this issue since I've only hit this since moving to the react-monaco-editor package and I'm the second person to hit the same issue. Hopefully someone who better understands webpack loaders and css modules will be able to give a recommendation :)

**Comment by domoritz** [comment] 2018-07-30 21:50
Thanks for doing this!

**Comment by TheRealPiotrP** [comment] 2018-08-02 23:36
I was able to work around the issue in my project. I needed for my app's css to be processed by                         `loader: "typings-for-css-modules-loader?modules"`. However, this breaks processing of monaco's css. I therefore gave my css files a unique file name suffix `.app.css` and forked my loader behavior between my css and `other` css. The following in webpack.config worked for me:

```
{
                test: /\.app.css$/,
                use: [  
                    {
                        loader: "typings-for-css-modules-loader?modules",
                        options: {
                            sourceMap: true,
                            importLoaders: 3,
                            modules: true,
                            namedExport: true,
                            camelCase: true
                        }
                    }
                ]
            },
            {
                test: /^((?!\.app).)*.css$/,
                use: [
                    { loader: MiniCssExtractPlugin.loader },
                    { loader: "css-loader" }
                ]
            },
```

**Comment by pankajsharma89** [comment] 2018-08-27 13:08
TheRealPiotrP how did you solved this problem I am also facing the same issue ?

How you added the suffix for your application CSS files.

Can you please share your web pack config for the same ?

Looking for your reply.

**Comment by BananaBobby** [comment] 2019-01-15 14:07
This helped in my case:

```
const path = require('path');
const APP_DIR = path.resolve(__dirname, './src');
const MONACO_DIR = path.resolve(__dirname, './node_modules/monaco-editor');
```

And in webpack config:
```
{
      test: /\.css$/,
      include: APP_DIR,
      use: [{
        loader: 'style-loader',
      }, {
        loader: 'css-loader',
        options: {
          modules: true,
          namedExport: true,
          localIdentName: '[name]-[local]-[hash:base64:5]',
        },
      }],
    }, {
      test: /\.css$/,
      include: MONACO_DIR,
      use: [{
        loader: 'style-loader',
      }, {
        loader: 'css-loader',
      }],
    }
```

**Comment by BananaBobby** [comment] 2019-01-15 14:43
I guess the issue is that monaco-editor doesn't use css modules internally, so if you have them added in your webpack config - it breaks monaco css imports. Having them separated to use different loaders setup fixes the issue.

**Comment by domoritz** [comment] 2019-01-15 14:48
I see. That's not really something we can fix here, though. Thanks for digging into this. Hopefully, people find this github issue when they run into similar problems.

**Comment by BananaBobby** [comment] 2019-01-15 14:52
Yeah, for sure. Maybe mentioning that in the Using with Webpack readme section could save people some time, what do you think?

**Comment by domoritz** [comment] 2019-01-17 04:38
Can you send a PR with some updates to the readme that explain what to do?

**Closed** 2019-01-19 01:18 UTC
